import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Alert, Button } from '../components/ui'
import { assistantApi, conversationsKey, type Conversation } from '../features/assistant/api'
import { ApiError } from '../lib/api'

const prompts = ['What does blood pressure mean?', 'How should I understand my latest HealthSphere assessment?', "What does 'not clinically calibrated' mean?"]

export function AssistantRoute() {
  const queryClient = useQueryClient(); const [params] = useSearchParams(); const assessmentId = params.get('assessment') ?? undefined
  const conversations = useQuery({ queryKey: conversationsKey, queryFn: assistantApi.list })
  const [selectedId, setSelectedId] = useState<string>(); const [draft, setDraft] = useState(assessmentId ? (prompts[1] ?? '') : '')
  const selected = conversations.data?.items.find((item) => item.id === selectedId)
  const create = useMutation({ mutationFn: assistantApi.create })
  const send = useMutation({ mutationFn: async (content: string) => { const conversation = selected ?? await create.mutateAsync(); setSelectedId(conversation.id); return assistantApi.send(conversation.id, content, assessmentId) }, onSuccess: (conversation) => { queryClient.setQueryData(conversationsKey, (current: { items: Conversation[]; next_cursor: string | null } | undefined) => ({ items: [conversation, ...(current?.items ?? []).filter((item) => item.id !== conversation.id)], next_cursor: current?.next_cursor ?? null })); setDraft('') } })
  const busy = create.isPending || send.isPending; const submit = () => { const message = draft.trim(); if (message && !busy) send.mutate(message) }
  return <main id="main-content" className="assistant-page"><header className="assistant-heading"><p className="eyebrow">Health information</p><h1>HealthSphere Assistant</h1><p>Provides general health information and can explain your HealthSphere results. It does not provide diagnosis or treatment.</p></header><div className="assistant-layout"><aside className="conversation-list" aria-label="Conversation history"><div><h2>Conversations</h2><Button variant="secondary" type="button" onClick={() => setSelectedId(undefined)}>New</Button></div>{conversations.isPending && <p role="status">Loading history…</p>}{conversations.isError && <p>Conversation history is unavailable.</p>}{conversations.data?.items.map((conversation) => <button type="button" key={conversation.id} className={conversation.id === selectedId ? 'active' : ''} onClick={() => setSelectedId(conversation.id)}><strong>{conversation.messages[0]?.content ?? 'New conversation'}</strong><time dateTime={conversation.updated_at}>{new Date(conversation.updated_at).toLocaleDateString()}</time></button>)}</aside><section className="assistant-panel" aria-labelledby="conversation-title"><h2 id="conversation-title" className="sr-only">Current conversation</h2><MessageArea conversation={selected} pending={busy} />{send.isError && <AssistantError error={send.error} />}<div className="assistant-composer"><label htmlFor="assistant-message">Ask HealthSphere Assistant</label><textarea id="assistant-message" value={draft} maxLength={2000} rows={3} disabled={busy} onChange={(event) => setDraft(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit() } }} placeholder="Type a health information question…" /><div><span>{draft.length} / 2000</span><Button type="button" loading={busy} disabled={!draft.trim()} onClick={submit}>Send</Button></div></div></section></div></main>
}

function MessageArea({ conversation, pending }: { conversation: Conversation | undefined; pending: boolean }) {
  const end = useRef<HTMLDivElement>(null); useEffect(() => { end.current?.scrollIntoView({ block: 'nearest' }) }, [conversation, pending])
  if (!conversation?.messages.length) return <div className="assistant-empty"><h2>What can I help explain?</h2><p>Ask a general health question or ask about a saved HealthSphere result.</p><ul>{prompts.map((prompt) => <li key={prompt}>{prompt}</li>)}</ul>{pending && <p role="status" aria-live="polite">HealthSphere is preparing a response…</p>}</div>
  return <div className="message-area" aria-live="polite">{conversation.messages.map((message) => <article key={message.id} className={`assistant-message assistant-message--${message.role} ${message.response_type === 'urgent' ? 'assistant-message--urgent' : ''}`} role={message.response_type === 'urgent' ? 'alert' : undefined}><p className="assistant-message__author">{message.role === 'user' ? 'You' : 'HealthSphere Assistant'}</p><p>{message.content}</p>{message.response_type === 'abstention' && <p className="response-label">The Assistant abstained because it could not answer safely.</p>}{message.uncertainty && <p className="uncertainty">Uncertainty: {message.uncertainty}</p>}{message.sources.length > 0 && <section className="assistant-sources"><h3>Sources</h3><ul>{message.sources.map((source) => <li key={source.source_id}>{source.url ? <a href={source.url} target="_blank" rel="noreferrer">{source.title}</a> : <span>{source.title}</span>}</li>)}</ul></section>}</article>)}{pending && <p className="assistant-generating" role="status">HealthSphere is preparing a response…</p>}<div ref={end} /></div>
}
function AssistantError({ error }: { error: Error }) { const unavailable = error instanceof ApiError && (error.status === 503 || error.code === 'agent_unavailable'); const session = error instanceof ApiError && error.status === 401; return <Alert tone="error">{session ? 'Your session has expired. Please log in again.' : unavailable ? 'The Assistant is temporarily unavailable. Your message was not saved.' : 'We could not send your message. Please try again.'}</Alert> }
